import "./reset.css"
import './input.css'
import './output.css'
import HeaderTop from "./components/Header/HeaderTop"
import HeaderBottom from "./components/Header/HeaderBottom"

export const metadata = {
  title: 'Blog Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-ubuntu text-default'>
        <HeaderTop/>
        <HeaderBottom/>
        {children}
        </body>
    </html>
  )
}
